spring:
  devtools:
    restart:
      enabled: false
  datasource:
    hikari:
      test1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test1
        username: root
        password: 123
      test2:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test2
        username: root
        password: 123
